### ISSUE TITLE
GC race with dirty bit

### ISSUE THREAD

**Issue by jeffmurphy** [UBMLtonGroup/RTMLton#15]
bhargav to enter description

**Comment by bhargavshivkumar** [comment]
Issue was that if some mutator was blocked when GC is running due to insufficient chunks, GC sent out a signal to unblock it before releasing RTSYNC lock. Thus if blocked mutator receives signal before GC unlocks RTSYNC lock, it would not perform GC_collect(since RTSYNC is checked in GC_collect by mutator) and thus not set dirty bit or mark its stack when blocking the next time. 

Solution: send out signal to mutators after releasing RTSYNC lock
